
part number ${devtype} ${devnum} hassos-boot boot_partnum
${devtype} dev ${devnum}
setenv fitimg_addr_r 280000
setenv loadbootstate " \
    echo 'loading env...'; \
    load ${devtype} ${devnum}:${boot_partnum} ${ramdisk_addr_r} uboot.env; \
    env import -c ${ramdisk_addr_r} 0x10000;"

setenv storebootstate " \
    echo 'storing env...'; \
    env export -c -s 0x10000 ${ramdisk_addr_r} loadkernel bootargs BOOT_ORDER BOOT_A_LEFT BOOT_B_LEFT MACHINE_ID; \
    fatwrite ${devtype} ${devnum}:${boot_partnum} ${ramdisk_addr_r} uboot.env 0x10000;"

run loadbootstate
test -n "${BOOT_ORDER}" || setenv BOOT_ORDER "A B"
test -n "${BOOT_A_LEFT}" || setenv BOOT_A_LEFT 3
test -n "${BOOT_B_LEFT}" || setenv BOOT_B_LEFT 3

# Allows ConditionFirstBoot=
if test -z "${MACHINE_ID}"; then
  setenv BOOT_CONDITION "systemd.condition-first-boot=true"
  setenv bootargs
  run storebootstate
else
  setenv BOOT_CONDITION
fi

# HassOS bootargs
setenv bootargs_hassos "earlycon=uart8250,mmio32,0xff1a0000 zram.enabled=1 zram.num_devices=3 systemd.machine_id=${MACHINE_ID} fsck.repair=yes ${BOOT_CONDITION}"

# HassOS system A/B
setenv bootargs_a "root=PARTUUID=e31b826a-52b9-4bec-946b-63a1893373c9 ro rootwait"
setenv bootargs_b "root=PARTUUID=a7d2e7ad-b081-4d6b-9f37-a986aebfd921 ro rootwait"


# Load environment from haos-config.txt
if test -e ${devtype} ${devnum}:${boot_partnum} haos-config.txt; then
  fatload ${devtype} ${devnum}:${boot_partnum} ${ramdisk_addr_r} haos-config.txt
  env import -t ${ramdisk_addr_r} ${filesize}
fi

setenv slot_tried ""
for BOOT_SLOT in ${BOOT_ORDER}; do
  if test "x${bootargs}" != "x"; then
    # skip remaining slots
  elif test "x${BOOT_SLOT}" = "xA"; then
    if test ${BOOT_A_LEFT} -gt 0; then
      setexpr BOOT_A_LEFT ${BOOT_A_LEFT} - 1
      setenv slot_tried "A"
      setenv bootargs
      echo "Trying to boot slot A, ${BOOT_A_LEFT} attempts remaining. Loading kernel ..."
      part number ${devtype} ${devnum} hassos-kernel0 kernel_partnum
      if load ${devtype} ${devnum}:${kernel_partnum} ${fitimg_addr_r} fit-Image.itb; then
          setenv loadkernel "load ${devtype} ${devnum}:${kernel_partnum} ${fitimg_addr_r} fit-Image.itb" 
          setenv bootargs "${bootargs_hassos} ${bootargs_a} rauc.slot=A ${cmdline}"
      fi
    fi
  elif test "x${BOOT_SLOT}" = "xB"; then
    if test ${BOOT_B_LEFT} -gt 0; then
      setexpr BOOT_B_LEFT ${BOOT_B_LEFT} - 1
      setenv slot_tried "B"
      setenv bootargs
      echo "Trying to boot slot B, ${BOOT_B_LEFT} attempts remaining. Loading kernel ..."
      part number ${devtype} ${devnum} hassos-kernel1 kernel_partnum
      if load ${devtype} ${devnum}:${kernel_partnum} ${fitimg_addr_r} fit-Image.itb; then
          setenv loadkernel "load ${devtype} ${devnum}:${kernel_partnum} ${fitimg_addr_r} fit-Image.itb"
          setenv bootargs "${bootargs_hassos} ${bootargs_b} rauc.slot=B ${cmdline}"
      fi
    fi
  fi
done


if test "x${slot_tried}" != "x"; then
  run storebootstate
else
  run loadkernel
fi

if test -z "${bootargs}"; then
  echo "No valid slot found, resetting tries to 3"
  setenv BOOT_A_LEFT 3
  setenv BOOT_B_LEFT 3
  run storebootstate
  reset
fi

echo "Starting kernel"
bootm ${fitimg_addr_r}

echo "Boot failed, resetting..."
