name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          submodules: true

    - name: Install QEMU and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libconfuse-dev qemu-user-static make gcc u-boot-tools mtools erofs-utils
        pip install pyelftools
  
    - name: build H618-k2b
      run: make H618-k2b

    - name: build RK3399-custom
      run: make rk3399-custom

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-outputs
        path: |
          out/images/haos*.img

        retention-days: 7          # 自定义保留天数[7](@ref)
