name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
          submodules: true

    - name: Install QEMU and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libconfuse-dev qemu-user-static make gcc u-boot-tools mtools
        pip install pyelftools
  
    - name: Install dependencies
      run: make
